services:
  nginx:
    build: 
      context: ./docker/nginx
      dockerfile: Dockerfile
    image: nginx-lt:01
    container_name: nginx-lt1
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./:/var/www
    networks:
      - lar
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        user: sammy
        uid: 1000
    image: php-fpm-test:01
    container_name: php-fpm-lar1
    ports:
      - 5173:5173
    volumes:
      - ./:/var/www
    networks:
      - lar 
  pgsql:
    build:
      context: ./docker/pgsql
      dockerfile: Dockerfile
    image: postgres-test:15  
    env_file:
      - .env
    ports:
      - '${DB_PORT:-5432}:5432'
    environment:
        PGPASSWORD: ${DB_PASSWORD:-secret}
        POSTGRES_DB: ${DB_DATABASE:-lpmanager}
        POSTGRES_USER: ${DB_USERNAME:-postgres}
        POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
    volumes:
        - '../pgsql-data:/var/lib/postgresql/data'
        - './docker/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
    networks:
            - lar
    healthcheck:
        test:
            - CMD
            - pg_isready
            - '-q'
            - '-d'
            - '$${DB_DATABASE}'
            - '-U'
            - '$${DB_USERNAME}'
        retries: 3
        timeout: 5s

networks:
  lar:
    driver: bridge
  